# Extracting Tweets

This notebook will extract tweets directly from twitter API.

This notebook will not run until you have predefined csv file to overwrite it.
This notebook will not run until you input your API parameter(Token key, etc)

In [4]:
# Importing Relevant packages
import pandas as pd
import re

from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer
from nltk import FreqDist
from nltk.corpus import stopwords

from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

In [ ]:
#!pip install tweepy
#!pip install twarc

In [5]:
from tweepy import OAuthHandler
#from tweepy.streaming import StreamListener
import tweepy
import json
import pandas as pd
import csv
import re
#from textblob import TextBlob
import string
#import preprocessor as p
import os
import time
#from twarc import expansions

import warnings
warnings.filterwarnings('ignore')

In [6]:
client = tweepy.Client(bearer_token='AAAAAAAAAAAAAAAAAAAAACOiiwEAAAAA0DTQdL04ru%2BAgRlxZpfpPnE0wSc%3D2BpVXMLarl7j0yqzJrfMRZM07p3guUMF491Uda9oJ7QyTF2KEi', 
                       consumer_key='ol9revN421BerUQe3Az68n7JL', 
                       consumer_secret='Y2vpWK4ZZrfB7C6UMIsltZBTD1cjPRjx4I7ONPQnjZDFtz7PYV', 
                       access_token='1572939670274678785-ESljwpipc48c5yMZVb8Mne6PaYpxWA', 
                       access_token_secret='6wHHc0koOhdI3DGnyYJHB1mq5RXZ1HQHzUquoZDjartAG', 
                       wait_on_rate_limit=False)

In [7]:
# using get_user with user name
username = "elonmusk"
user = client.get_user(username=username)
print(f"The user name for user name {username} is {user.data.id}.")

The user name for user name elonmusk is 44196397.

In [8]:
def gettweettext(tweet_id_lists):
    # This function should take a list of tweet ids, get the text from Twitter
    # and save the resulting text as a tuple of tweet id, tweet text.
    # Make sure to create a tweepy Client instance called 'client' to use.

    output_list = []
    for i in tweet_id_lists:
        tweet = client.get_tweet(i)
        tweet_id = i
        tweet_tuple = (tweet_id, str(tweet.data)) 
        output_list.append(tweet_tuple)
    return output_list

In [9]:
gettweettext([44196397])

[(44196397, 'None')]

The cell below is the criteria I used to extract tweets

With the Current license that I used, the cell below only can get tweets from 7 days before ago!

In [10]:
query = 'elon musk twitter lang:en -is:retweet'
start_time = '2022-10-30T12:00:00Z'
#end_time = '2022-11-03T12:00:00Z'

tweets = client.search_recent_tweets(query = query, max_results=10, start_time=start_time)

BadRequest: 400 Bad Request
Invalid 'start_time':'2022-10-30T12:00Z'. 'start_time' must be on or after 2022-11-09T22:23Z

In [2]:
df= pd.DataFrame(tweets[0])
df.drop(columns='edit_history_tweet_ids', axis=1, inplace=True)
df.to_csv('Data/tweets.csv', index=False)

NameError: name 'tweets' is not defined

In [9]:
# Loading the dataframe before running the next block function!
df=pd.read_csv('Data/tweets.csv')

In [13]:
def gettweets(saved_df,hours):
    '''
    This function will iterate over 5 minutes time periods and fetch 100 tweets and append the dataframe,
    then save it to csv file for the overal hours specified in the function.
    
    '''    
    
    i = hours*12
    while i > 0:
        print("Extracting tweets...")
        saved_df = pd.read_csv('tweets.csv')
        tweets = client.search_recent_tweets(query = query, max_results=100, since_id=saved_df.id.iloc[-1],)
        print("100 tweets extracted" )
        df= pd.DataFrame(tweets[0])
        df.drop(columns='edit_history_tweet_ids', axis=1, inplace=True)
        tweets_df = saved_df.append(df)
        tweets_df.to_csv('Data/tweets.csv', index=False)
        i -= 1
        print(tweets_df.info())
        print(f'Extracted tweets: {len(tweets_df)}' )
        time.sleep(60*5.15)
    return "Done!"

In [19]:
# Fetching tweets from user API created for number of hours specified

gettweets(df,6)

Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23248 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23248 non-null  int64
 1   text      23248 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 726.5+ KB
None
Extracted tweets: 23248
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23347 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23347 non-null  int64
 1   text      23347 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 729.6+ KB
None
Extracted tweets: 23347
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23447 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23447 non-null  int64
 1   text      23447 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 732.7+ KB
None
Extracted tweets: 23447
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23546 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23546 non-null  int64
 1   text      23546 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 735.8+ KB
None
Extracted tweets: 23546
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23646 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23646 non-null  int64
 1   text      23646 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 738.9+ KB
None
Extracted tweets: 23646
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23746 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23746 non-null  int64
 1   text      23746 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 742.1+ KB
None
Extracted tweets: 23746
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23846 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23846 non-null  int64
 1   text      23846 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 745.2+ KB
None
Extracted tweets: 23846
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23945 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        23945 non-null  int64
 1   text      23945 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 748.3+ KB
None
Extracted tweets: 23945
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24045 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24045 non-null  int64
 1   text      24045 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 751.4+ KB
None
Extracted tweets: 24045
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24145 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24145 non-null  int64
 1   text      24145 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 754.5+ KB
None
Extracted tweets: 24145
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24245 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24245 non-null  int64
 1   text      24245 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 757.7+ KB
None
Extracted tweets: 24245
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24345 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24345 non-null  int64
 1   text      24345 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 760.8+ KB
None
Extracted tweets: 24345
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24445 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24445 non-null  int64
 1   text      24445 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 763.9+ KB
None
Extracted tweets: 24445
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24545 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24545 non-null  int64
 1   text      24545 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 767.0+ KB
None
Extracted tweets: 24545
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24645 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24645 non-null  int64
 1   text      24645 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 770.2+ KB
None
Extracted tweets: 24645
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24745 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24745 non-null  int64
 1   text      24745 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 773.3+ KB
None
Extracted tweets: 24745
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24845 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24845 non-null  int64
 1   text      24845 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 776.4+ KB
None
Extracted tweets: 24845
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24945 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24945 non-null  int64
 1   text      24945 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 779.5+ KB
None
Extracted tweets: 24945
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25045 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25045 non-null  int64
 1   text      25045 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 782.7+ KB
None
Extracted tweets: 25045
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25145 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25145 non-null  int64
 1   text      25145 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 785.8+ KB
None
Extracted tweets: 25145

Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25245 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25245 non-null  int64
 1   text      25245 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 788.9+ KB
None
Extracted tweets: 25245
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25345 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25345 non-null  int64
 1   text      25345 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 792.0+ KB
None
Extracted tweets: 25345
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25445 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25445 non-null  int64
 1   text      25445 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 795.2+ KB
None
Extracted tweets: 25445
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25545 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25545 non-null  int64
 1   text      25545 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 798.3+ KB
None
Extracted tweets: 25545
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25645 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25645 non-null  int64
 1   text      25645 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 801.4+ KB
None
Extracted tweets: 25645
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25745 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25745 non-null  int64
 1   text      25745 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 804.5+ KB
None
Extracted tweets: 25745
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25845 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25845 non-null  int64
 1   text      25845 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 807.7+ KB
None
Extracted tweets: 25845
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25945 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        25945 non-null  int64
 1   text      25945 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 810.8+ KB
None
Extracted tweets: 25945
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26045 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26045 non-null  int64
 1   text      26045 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 813.9+ KB
None
Extracted tweets: 26045
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26145 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26145 non-null  int64
 1   text      26145 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 817.0+ KB
None
Extracted tweets: 26145
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26244 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26244 non-null  int64
 1   text      26244 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 820.1+ KB
None
Extracted tweets: 26244
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26343 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26343 non-null  int64
 1   text      26343 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 823.2+ KB
None
Extracted tweets: 26343
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26443 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26443 non-null  int64
 1   text      26443 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 826.3+ KB
None
Extracted tweets: 26443
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26543 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26543 non-null  int64
 1   text      26543 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 829.5+ KB
None
Extracted tweets: 26543
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26643 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26643 non-null  int64
 1   text      26643 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 832.6+ KB
None
Extracted tweets: 26643
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26743 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26743 non-null  int64
 1   text      26743 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 835.7+ KB
None
Extracted tweets: 26743
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26843 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26843 non-null  int64
 1   text      26843 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 838.8+ KB
None
Extracted tweets: 26843
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 26943 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        26943 non-null  int64
 1   text      26943 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 842.0+ KB
None
Extracted tweets: 26943
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27043 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27043 non-null  int64
 1   text      27043 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 845.1+ KB
None
Extracted tweets: 27043
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27142 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27142 non-null  int64
 1   text      27142 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 848.2+ KB
None
Extracted tweets: 27142

Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27242 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27242 non-null  int64
 1   text      27242 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 851.3+ KB
None
Extracted tweets: 27242
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27341 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27341 non-null  int64
 1   text      27341 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 854.4+ KB
None
Extracted tweets: 27341
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27440 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27440 non-null  int64
 1   text      27440 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 857.5+ KB
None
Extracted tweets: 27440
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27540 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27540 non-null  int64
 1   text      27540 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 860.6+ KB
None
Extracted tweets: 27540
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27640 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27640 non-null  int64
 1   text      27640 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 863.8+ KB
None
Extracted tweets: 27640
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27740 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27740 non-null  int64
 1   text      27740 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 866.9+ KB
None
Extracted tweets: 27740
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27840 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27840 non-null  int64
 1   text      27840 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 870.0+ KB
None
Extracted tweets: 27840
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27940 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        27940 non-null  int64
 1   text      27940 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 873.1+ KB
None
Extracted tweets: 27940
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28040 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28040 non-null  int64
 1   text      28040 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 876.2+ KB
None
Extracted tweets: 28040
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28140 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28140 non-null  int64
 1   text      28140 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 879.4+ KB
None
Extracted tweets: 28140
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28240 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28240 non-null  int64
 1   text      28240 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 882.5+ KB
None
Extracted tweets: 28240
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28340 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28340 non-null  int64
 1   text      28340 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 885.6+ KB
None
Extracted tweets: 28340
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28440 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28440 non-null  int64
 1   text      28440 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 888.8+ KB
None
Extracted tweets: 28440
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28539 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28539 non-null  int64
 1   text      28539 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 891.8+ KB
None
Extracted tweets: 28539
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28639 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28639 non-null  int64
 1   text      28639 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 895.0+ KB
None
Extracted tweets: 28639
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28739 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28739 non-null  int64
 1   text      28739 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 898.1+ KB
None
Extracted tweets: 28739
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28839 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28839 non-null  int64
 1   text      28839 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 901.2+ KB
None
Extracted tweets: 28839
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 28939 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        28939 non-null  int64
 1   text      28939 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 904.3+ KB
None
Extracted tweets: 28939
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29037 entries, 0 to 97
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29037 non-null  int64
 1   text      29037 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 907.4+ KB
None
Extracted tweets: 29037
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29137 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29137 non-null  int64
 1   text      29137 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 910.5+ KB
None
Extracted tweets: 29137

Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29236 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29236 non-null  int64
 1   text      29236 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 913.6+ KB
None
Extracted tweets: 29236
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29336 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29336 non-null  int64
 1   text      29336 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 916.8+ KB
None
Extracted tweets: 29336
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29436 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29436 non-null  int64
 1   text      29436 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 919.9+ KB
None
Extracted tweets: 29436
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29536 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29536 non-null  int64
 1   text      29536 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 923.0+ KB
None
Extracted tweets: 29536
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29636 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29636 non-null  int64
 1   text      29636 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 926.1+ KB
None
Extracted tweets: 29636
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29736 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29736 non-null  int64
 1   text      29736 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 929.2+ KB
None
Extracted tweets: 29736
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29836 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29836 non-null  int64
 1   text      29836 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 932.4+ KB
None
Extracted tweets: 29836
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 29936 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        29936 non-null  int64
 1   text      29936 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 935.5+ KB
None
Extracted tweets: 29936
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30036 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        30036 non-null  int64
 1   text      30036 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 938.6+ KB
None
Extracted tweets: 30036
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30136 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        30136 non-null  int64
 1   text      30136 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 941.8+ KB
None
Extracted tweets: 30136
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30235 entries, 0 to 98
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        30235 non-null  int64
 1   text      30235 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 944.8+ KB
None
Extracted tweets: 30235
Extracting tweets...
100 tweets extracted
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30335 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        30335 non-null  int64
 1   text      30335 non-null  object
 2   withheld  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 948.0+ KB
None
Extracted tweets: 30335

'Done!'